### ISSUE TITLE
Component error: modbus - cannot import name 'Defaults' from 'pymodbus.constants' (/usr/local/lib/python3.11/site-packages/pymodbus/constants.py)

### ISSUE THREAD

**Issue by denzelm5** [sfstar/hass-victron#112]
Good Day,

Home Assistant 2023.8.3
Supervisor 2023.08.1
Operating System 10.5
Frontend 20230802.1 - latest

Victron Integration : latest 

I got this issue this morning : 

Updating state for sensor.victron_solarcharger_tracker_2_pv_power_1 (<class 'custom_components.victron.sensor.VictronSensor'>) took 0.726 seconds. Please report it to the custom integration author.
9:08:19 AM – (WARNING) helpers/entity.py
Error while setting up victron platform for number
9:04:52 AM – (ERROR) Number (custom integration)
TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ states('sensor.victron_tank_remaining_21')|float() }}' but no default was specified') while processing template 'Template<template=({{ states('sensor.victron_tank_remaining_21')|float() }}) renders=5478>' for attribute '_attr_native_value' in entity 'sensor.jojo_1'
9:04:50 AM – (ERROR) helpers/template_entity.py - message first occurred at 9:04:50 AM and shows up 3 times

Regards

**Comment by nicofamdj** [comment]
I can confirm after last update:

Setup failed for modbus: Unable to import component: cannot import name 'Defaults' from 'pymodbus.constants' (/usr/local/lib/python3.11/site-packages/pymodbus/constants.py)

Victron is working, but my modbus in confguration.yaml is not working anymore after update to 0.1.3

After reverting back to 0.1.2 my modbus config is working again (aswell as the victron*)
*) sometimes this error (0.1.2):
Setup failed for custom integration victron: Unable to import component: cannot import name 'make_byte_string' from 'pymodbus.utilities' (/usr/local/lib/python3.11/site-packages/pymodbus/utilities.py)

**Comment by peregrines2** [comment]
Same here :(

**Comment by smout74** [comment]
Unfortunately +1 on the error:

Setup failed for modbus: Unable to import component: cannot import name 'Defaults' from 'pymodbus.constants' (/usr/local/lib/python3.11/site-packages/pymodbus/constants.py)

**Comment by wasn-eu** [comment]
same here

**Comment by wasn-eu** [comment]
now my normal modbus and victron is not working anymore.
We need a quick fix

**Comment by sfstar** [comment]
Sorry that i'm unable to quickly patch issues with this integration at the moment.
In case of issues with a new release you can also select redownload integration in hacs and download an older version again until a fix comes out

**Comment by smout74** [comment]
After upgrading to HASS 2023.8.4 and re-installing this version 0.1.3, for me the issue seems to be solved. Both the Victron and normal modbus (Energy kWh meters Hiking via tcp and standard HASS modbus) seem to be working and updating as normal. 

It's running like this for 50+ hours, no complaints anymore.

**Comment by sfstar** [comment]
Please test the beta v0.1.4 release of this interation (this is a copy paste reply which isn't customized for each issue v.0.1.4 is attempting to adres).
Make sure that (in cae this applies to you) the core modbus integration is also fully enabled after bumping to version 0.1.4 and let me know if the issue persists.

**Comment by denzelm5** [comment]
Hi ,

beta v0.1.4 broke the entire intergration in that it couldnt start the intergration ,

Regards
________________________________

**Comment by peregrines2** [comment]
Here too :(
After installing the Beta an reenabling "modbus: !include modbus.yaml"
The system wont restart and gives an error :(

<img width="558" alt="Bildschirmfoto 2023-09-05 um 08 28 02" src="https://github.com/sfstar/hass-victron/assets/9152610/b8d96cce-1001-4f20-9af7-75c0ca1d67b0">

**Comment by peregrines2** [comment]
(after installing the Beta I was able to restart though)

**Comment by sfstar** [comment]
Later releases adressed the incompatibility between the HA core modbus integrations pymodbus version being used and this integrations pymodbus usage.
Therefore, closing issue for now.
Please re-open if the issue persists.
